AxonIQ/axonserver-connector-java

src/main/java/io/axoniq/axonserver/connector/ResultStream.java
src/main/java/io/axoniq/axonserver/connector/impl/AbstractBufferedStream.java
src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledBuffer.java
src/test/java/io/axoniq/axonserver/connector/impl/BufferedStreamTest.java

It was impossible for a client to get the root cause of a stream being closed, as the exception reported when closing a stream was not exposed. This commit adds a method to the ResultStream which exposes the reported error.

Expose the cause of closing on a BufferedStream

---

pom.xml

According to the table at https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty, the latest available combination for gRPC and Netty TC Native is `1.32.x-...` for gRPC and `2.0.31.Final` for Netty TC Native

Update gRPC and Netty TCNative to latest (compatible) versions

---

src/main/java/io/axoniq/axonserver/connector/event/AggregateEventStream.java
src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
src/test/java/io/axoniq/axonserver/connector/event/EventHandlingTest.java
src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java

This commit fixes an issue where errors reported while reading events for an aggregate aren't reported to the consumer. Instead, the consumer receives an empty or incomplete stream, based on which it could make false assumptions.

Ensure that error reading events for agggregate are propagated

---

src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
src/main/java/io/axoniq/axonserver/connector/impl/StreamUnexpectedlyCompletedException.java
src/test/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStreamTest.java

Copy of #26, but just containing the fixes and not the accidental addition of master.
Adds the invocation of the `disconnectHandler` if `onCompleted` had `AbstractIncomingInstructionStream#unregisterOutboundStream` return `true`.

Client reconnect when stream is completed unexpectedly by the server. 

---

src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/command/CommandChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/command/CommandChannelTest.java
src/test/java/io/axoniq/axonserver/connector/event/EventHandlingIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java

Some exceptions (mainly those not extending from StatusRuntimeException) would not put the Connector in a state where it recognizes the connection is in an error state. As a result, it would allow calls to be triggered from the various Connector Channels, which then resulted in exceptions.
This change ensures that failed connect attempts are recognized as such and will prevent calls from being sent.
When calls _are_ sent, they now behave exactly the same way as calls using the grpc library's own ManagedChannel should behave. That means messages towards the server are ignored and calls immediately (exceptionally) completed with a Status exception.

Fix subscribe when disconnected

---

src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
src/main/java/io/axoniq/axonserver/connector/impl/ContextConnection.java
src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStreamTest.java
src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java

This PR addresses a race condition that can occur when setting up a connection that fails in a very short period of time. In such a case, the connector could believe it still has a valid connection with Axon Server.
Logging has been improved to include the name of context for which the message applies.

Connector connection recovery improvement

---

src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java

Validates that events are received in the correct order, without any gap, checking if the aggregateSequenceNumbers are sequential.

Aggregate sequence number validation 

---

src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/impl/AssertUtils.java
src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledStream.java
src/main/java/io/axoniq/axonserver/connector/impl/SynchronizedRequestStream.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java
src/test/java/io/axoniq/axonserver/connector/impl/BufferedStreamTest.java
src/test/java/io/axoniq/axonserver/connector/impl/FlowControlledBufferTest.java
src/test/java/io/axoniq/axonserver/connector/impl/FlowControlledStreamTest.java
src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java

Added manual grpc-level flow control on all server-side streaming responses. This means that even for the requests where flow control isn't (or cannot) be managed from the application level messages, the flow of messages is adapted to the desired size of the client-side buffers.

Added grpc-level flow control to all streaming calls

---

src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java

Remove the aggregate sequence number validation in favour of the same validation in AxonServer. This fix also the invocation of the endpoint for retrieving multiple snapshots that, of course, has no sequential aggregate sequence numbers.

Remove aggregate sequence validation

---

src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/command/CommandChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java

This commit introduces a forced reconnect when the control channel
receives an UNAVAILABLE error while the connection is still active. This
likely indicates a proxy keeps the connection alive, while unable to
forward call to the backing service.
By forcing a reconned, the connector will reconnect using all available
servers, instead of waiting for the calls on the previous connection to
succeed.

Improved connection recovery when using proxies

---

src/main/java/io/axoniq/axonserver/connector/event/EventChannel.java
src/main/java/io/axoniq/axonserver/connector/event/EventQueryResultEntry.java
src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/event/EventHandlingIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/testutils/MessageFactory.java

This PR introduces the ad-hoc query API for events and snapshots to the AxonServer connector.

Implemented ad-hoc query API for events

---

src/main/java/io/axoniq/axonserver/connector/AxonServerConnectionFactory.java
src/main/java/io/axoniq/axonserver/connector/ReplyChannel.java
src/main/java/io/axoniq/axonserver/connector/impl/ContextConnection.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java

Made number of permits for Command and Query Handlers configurable. Defaults to 5000.
Message identifier for Query and Subscription Query are optional. A random UUID is assigned when no identifier is provided.

Usability improvements

---

src/main/java/io/axoniq/axonserver/connector/ReplyChannel.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/query/impl/SubscriptionQueryStream.java
src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java

Solves an issue where permits weren't properly refreshed when receiving subscription query instructions.

Ensure refresh of permits on subscription query

---

pom.xml
src/main/java/io/axoniq/axonserver/connector/AxonServerConnectionFactory.java
src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
src/main/java/io/axoniq/axonserver/connector/impl/ContextConnection.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java

This PR introduces changes to the shutdown process that ensures connections can be reconnected to after a (manual) disconnect.
It also prevents some warnings from being logged as a result of calling `disconnect()` more than once.

Allow (re)connecting after a disconnect

---

src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java

complete the response channel when a query is cancelled by the requester

Fix permit leak on cancelled query

---

src/main/java/io/axoniq/axonserver/connector/impl/HeartbeatMonitor.java

Exceptions were not caught during sending the heartbeat. This can interrupt scheduling of the next check, effectively disabling heartbeats altogether. 
This PR adds a try/catch block with logging about the nature of the error, to improve resiliency

Correctly handle exceptions during heartbeat check

---

src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledBuffer.java
src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledStream.java
src/main/java/io/axoniq/axonserver/connector/impl/StreamTimeoutException.java
src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java

In some very special cases it seems the aggregate keeps loading indefinitely. This PR puts a timeout, by default 10 seconds, on waiting for the next event in the stream.
This timeout can be customized using the `AGGREGATE_TAKE_EVENT_TIMEOUT_MILLIS` system property.

Throw TimeoutException when loading next even for aggregate takes too long

---

src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java

This is the `4.5.x.` counterpart of #219.
In normal situations, the current implementation of `QueryChannelImpl.isReady()` is sufficient. However, in some very rare cases the channel stays connected, while being unable to register query handlers. Despite the failing registering of the handlers the `isReady()` check wrongfully believes it's health, since the `subscriptionsCompleted` is never set to false in case of errors.
This PR fixes this problem by setting it to false in the case of errors during registering, and setting it to false during disconnection. The boolean is then determined again when connecting and succeeding.
Note: During a normal disconnect, the outbound stream would be set to null, so it normally works in the way it should. This is for the abnormal situation where the …

Fix the subscriptionsCompleted boolean in query and command channels

---

pom.xml
src/main/java/io/axoniq/axonserver/connector/AxonServerConnectionFactory.java

gRPC-netty updated to 1.49.0 and matching tc-native modules to address [CVE-2021-22569](https://nvd.nist.gov/vuln/detail/CVE-2021-22569) in Protobuf
Slf4J API was downgraded to 1.7.36 as there is no working log4j provider for the 2.0.0 version yet.

Dependency updates

---

pom.xml
src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java

This pull request does two things, namely:
- Upgrading to the latest Testcontainers dependency
- Replacing use of OkHTTP3 for Apache HttpClient 5
The latter is a response to [#5113](https://github.com/testcontainers/testcontainers-java/pull/5113) from the testcontainers repository, which removed OkHTTP3 in favor of Apache HttpClient 5.
Moving through the issue landed me [here](https://github.com/docker-java/docker-java/blob/master/docs/transports.md#okhttp), which also points out that moving to Apache HttpClient 5 is a smart move.
Furthermore, changes had to be made regardless, as the aforementioned issue dropped the shaded dependency we were relying on.
Next to the above, this pull request resolves warnings and cleans the dependency set a little.
Doing so, this pull request replaces …

Upgrade Testcontainers dependency and replace OkHTTP3 for Apache HttpClient 5

---

src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedEventStream.java
src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledStream.java
src/main/java/io/axoniq/axonserver/connector/query/impl/SubscriptionQueryStream.java
src/test/java/io/axoniq/axonserver/connector/command/CommandChannelIntegrationTest.java

When opening an event stream, the client should provide the clientId and componentName to AxonServer, so that it can use these for reporting purposes.

Add clientId and componentName to events request

---

pom.xml
src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java

With the introduction of TestNG, the `maven-surefire-plugin` defaulted to *only* running the TestNG tests.
This pull request resolves that, by adding the `testng-junit5` dependency to the project, and by enforcing the `surefire-junit-platform` on the `maven-surefire-plugin`.
In doing so, issues arose in the Integration Tests.
The simplest one was reverting the `https` operations to `http` operations, as that's required within the IT's
More complex where the start, pause, split, merge, and move tests.
These had old assumptions on how to invoke the endpoints and how to reply to those, requiring a number of adjustments.

Ensure both TestNG and Jupiter tests are run

---

src/main/java/io/axoniq/axonserver/connector/command/CommandChannel.java
src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/control/ControlChannel.java
src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
src/main/java/io/axoniq/axonserver/connector/query/QueryChannel.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java

As mentioned in Axon Framework issue [2456](https://github.com/AxonFramework/AxonFramework/issues/2456), the use of unregister is incorrect use of the English language. 
Unregister may only be used if something was never registered to begin with. 
All occurrences are, however, describing the removal of an existing registration, which should be called deregister instead.
This pull request resolve this predicament for the `axonserver-connector-java` project.

Replace use of unregister for deregister

---

src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
src/main/java/io/axoniq/axonserver/connector/impl/ContextConnection.java
src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java

Whenever the `CommandChannelImpl` and `QueryChannelImpl` try to open a stream with their `CommandProviderOutbound` and `QueryProviderOutbound` respectively we should catch exceptions. 
Exceptions may occur when, for example, the connection to the Axon Server instance is down or faulty at that moment in time.
If we do not catch these exceptions, the channel implementations get stuck in a faulty state.
In this state, they've already created and their `StreamObserver` instance.
As the `StreamObserver` instance is used to deduce whether the connection is live, a following reconnect will be ignored. 
A consequence of this, is that the command and query handlers never get registered on a reconnect, resulting in the `NoHandlerForCommandException` and `NoHandlerForQueryException`
A user of the …

Clean up `StreamObserver` on failed `openStream` attempt to solve No Handlers Found exception

---

src/main/java/io/axoniq/axonserver/connector/AxonServerConnectionFactory.java
src/main/java/io/axoniq/axonserver/connector/impl/ServerAddress.java
src/test/java/io/axoniq/axonserver/connector/AxonServerConnectionFactoryTest.java

This pull request resolves the logic around the `suppressDownloadMessage` toggle.
This toggle is set to `true` on *any* invocation or `AxonServerConnectionFactory.Builder#routingServers`.
However, this invocation is *always* invoked, hence the download message never shows.
To resolve this, this pull request checks whether:
1. A single `ServerAddress` is provided, and
2. If so, check whether it is a default `ServerAddress` of host `localhost` and port `8124`.
Next to the default address validation, reintroduce the `axon.axonserver.suppressDownloadMessage` property check.
When set, retrieve the value set under this system property.
Lastly, a test is introduced to validate that the existing `axonserver_download.txt` is shared, yes/no.

Fix Download Message Suppression Logic

---

pom.xml
src/main/java/io/axoniq/axonserver/connector/AxonServerConnectionFactory.java
src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/event/EventHandlingIntegrationTest.java
src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java

The connector is too reliant on a specific combination of dependencies from grpc, netty and tcnative. Changing these dependencies ensures full compatibility, regardless of dependencies introduced by other libraries (e.g. Spring Boot).
This does, unfortunately, introduce a small API change. Some components have their package prefixed, such as the SSLContext. This may cause some usage of the connector to break, although the fix is very straightforward.
This PR also addresses some tests that were running against older versions of Axon Server

Introduced dependency on grpc-netty-shaded

---

src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java

Randomizing the order in which servers are used for connections prevents a misbehaving (e.g. out of sync) first candidate to prevent the application from connecting via other instances in the cluster.

Randomized connection order of servers

---

src/test/java/io/axoniq/axonserver/connector/AxonServerConnectionFactoryTest.java

Some connections were lingering, causing excessive logging of connection exceptions. This commit ensures that the connections are properly closed after the test.

Ensure connections are properly closed in tests

---

pom.xml

grpc doesn't transitively update protobuf beyond 3.x, so these have to be overridden explicitly for the time being.
I also ensured the protobug generator uses the same version as the protobuf library, to ensure any code optimizations are part of the generated code.

Updated grpc to 1.69.0 and protobuf to 4.29.2

---

pom.xml

The protobuf version was overridden for the build, but this was not forced to any upstream dependencies. That caused them to use protobuf 3.25, while the connector relies on 4.29.

Added explicit dependency to force protobuf update

---

src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedPersistentStreamSegment.java
src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
src/main/java/io/axoniq/axonserver/connector/event/impl/PersistentStreamImpl.java

By reporting an error to downstream consumers, they are notified of the fact that the disconnect didn't happen for normal reasons, and the stream should be reopened if the application wishes to continue processing events.
This avoids problems due to clients not reconnecting their persistent streams after a reconnect request from Axon Server. Applications need to be restarted to recover from this situation.
With this PR, clients are notified of the disconnect and may re-establish a connection.

PersistentStreams should be re-established on reconnect requests
